### ISSUE TITLE
request to work with other aligners

### ISSUE THREAD

**Issue by proukakis** [mroosmalen/nanosv#1]
Hello, I hope you dont mind me posting, and I am sure you are working on this already, but it would be great to have it for graphmap-aligned data, or bwa. Is this likely soon? thanks, christos

**Comment by mroosmalen** [comment]
NanoSV doesn't work on other aligners, because BWA and Graphmap doesn't report split alignments properly (at this moment).

**Comment by fritzsedlazeck** [comment]
How do I get the Last alignments into a bam format? Do I need special parameter for LAST or e.g. last-split?

**Comment by mroosmalen** [comment]
First you can train to get the best settings for your data, 10.000 reads should be enough

last-train -Q1 humandb reads-sample.fastq > my-params

The use the parameters for mapping:

lastal -Q1 -p my-params humandb reads.fastq | last-split > reads.maf

And then convert the maf format to a bam format ( you can also use pipes ):

maf-convert -d sam reads.maf | sambamba -S --format=bam /dev/stdin > reads.bam

**Comment by fritzsedlazeck** [comment]
Thanks

**Comment by QUEEFY** [comment]
Hey @mroosmalen quick question. You said BWA doesn't report split alignments properly. I noticed my BAM file has split alignments from BWA. Do you mind explaining as to why BWA is not supported but LAST is? Thanks :)

**Comment by mroosmalen** [comment]
We did not use BWA-MEM alignments as NanoSV input, because the reads are not always split in **non-overlapping** segments. 
More precisely, we observed that the following two (oversimplified) CIGAR strings may be produced, 
for two aligned segments originating from the same sequencing read: 6M4S and 4S6M respectively. 
While at least some of these alignments are marked as secondary by BWA and can be simply discarded from the analysis, 
we found that the LAST alignment splitting of the same reads leads, in some cases, 
to identification of otherwise high confidence structural variants.
