### ISSUE TITLE
BND and other SVtypes

### ISSUE THREAD

**Issue by wdecoster** [mroosmalen/nanosv#34]
Hi,

I might have missed it somewhere, but I don't understand how the BND SVtype relates to other SVtypes. As far as I understand it relates to a breakend (breakpoint?), which presumably flanks each SV? 
But not every DUP/DEL has a breakend?

I saw a recent answer (https://github.com/mroosmalen/nanosv/issues/33#issuecomment-396201553) also discussed something related, but it's not entirely clear to me how to interpret this, and moreover, how to compare a "BND" with SV calls from e.g. Sniffles.

Cheers,
Wouter

**Comment by jaesvi** [comment]
Hi Wouter,
We took the decision to not report SV types and rather report the breakpoints we find. Using the split alignments from the reads (or the gapped alignments for that matter), you will find these breakpoints. The step from breakpoint to SV type is then done based on the orientation of these breakpoints (for example, TH (3'-5') _usually_ marks a deletion, HH or TT marks inversions and HT marks duplications). But we found that in some samples (i.e. chromothripsis), a TH orientation does not necessarily indicate a deletion. This was creating interpretation errors, so we find it less error-prone to report breakpoints and leave to the user the interpretation of these breakpoints. 
An exception is then the _depth_support_ mode, where apart from the orientation we test if the coverage changes to be able to detect deletions and duplications.
I am not sure if I explained myself clearly enough, so feel free to keep enquiring.
Cheers,
Jose

**Comment by wdecoster** [comment]
Hi Jose,

Thanks for explaining! Perhaps you could add something like this to the README?

So, to make sure I understood correctly:

a variant in the vcf file is presented as (example)
`chr1    30696819        2718    T       T[chr1:30699183[        6       LowQual;MapQual IMPRECISE;SVTYPE=BND;`

This variant is defined by a pair of breakpoints, one at 30696819 and one at 30699183. Because there was no marked loss or gain in coverage this position was not annotated as DEL resp INS but as a BND.

I understand that in 'extreme' cases of chromothripsis your annotation using breakpoint orientation doesn't work out, but wouldn't it be possible to optionally activate it? I expect that the genomes I'm working on are -ahum- less messed-up and I gladly take an occasional inaccuracy over easier interpretable calls.

Would that make sense?

Cheers.
Wouter

**Comment by jaesvi** [comment]
We will include something in the README. We are preparing a new release with multithreading and gapped alignment support (hopefully next week) and we need to revise it anyway. 

From the way I use the terms, a breakpoint is defined by two breakends (BND). In the example you give: one at chr1 30696819 and another one at chr1 30699183. The orientation of these BNDs is defined as T[chr1:30699183[ (read more about reporting BND orientation at https://samtools.github.io/hts-specs/VCFv4.2.pdf ). So in this case the orientation is TH indeed, which is characteristic for DELs indeed. 
Imho, it is not possible to then discern between an intrachromosomal translocation and a deletion using only the information of one breakpoint, without taking into account coverage or something else. I will discuss with the rest of the team if we want to add this option though, because for some users it would indeed make sense. 

Best,
Jose

**Comment by wdecoster** [comment]
Hi Jose,

I'll start NanoSV for our NA19240 data as soon as I got your next release :)
Guess I have to read some more about these BNDs in the samtools specs.

Cheers,
Wouter

2018-06-15 16:36 GMT+02:00 Jose Espejo Valle-Inclan <
notifications@github.com>:
