### ISSUE TITLE
NanoSV takes too long parsing BAM file

### ISSUE THREAD

**Issue by fanavarro** [mroosmalen/nanosv#52]
Hi, we are trying NanoSV in order to identify structural variants in the human genome. We have sequenced a whole genome with MinION device and its software MinKNOW. Then we aligned the reads with GraphMap. This resulted in a 22GB BAM file. We generate a BED file from this BAM by using bedtools (bamToBed). Finally, we executed NanoSV with python3, using 32 cores and passing the previously generated BED and BAM files. Now, NanoSV is stuck with parsing the BAM file for 5 days, and it is using only one core. Is this normal? How much time could take NanoSV to parse a BAM file? We do not know if the program is hanged or if it continues parsing the file.

Thanks in advance.

Greetings,
Fran Abad.

**Comment by jaesvi** [comment]
Hi Fran,
We have not really tested NanoSV with BAM files resulting from GraphMap. The choice of mapper is important for NanoSV since we are looking for specific ways of encoding split and gapped mappings, and mapping tools vary in the way of reporting those. I would recommend to map with a different mapper, e.g.  minimap2 (https://github.com/lh3/minimap2) or NGMLR (https://github.com/philres/ngmlr). 
Also, I do not fully understand the BED file you generated from the BAM file. If you have a human genome (version hg19) I recommend to not give a BED file at all (NanoSV will take the one we provide by default to establish coverage at 1 million different positions). 
Finally, do you know approximately what is your coverage? Is the 22 GB gigabytes or Gbp (gigabasepairs)? Unfortunately, multi-threading in NanoSV is not very efficient at the moment, so giving it more cores will not help very much. 5 days parsing the BAM sounds like too much indeed unless you have extremely high coverage, which does not seem like the case. 

Saludos,
Jose

**Comment by fanavarro** [comment]
Hi Jose, thanks for your answer. We have just killed the process and we are going to try with minimap2. Also, we used a BED file generated from the BAM resulting from the reads, which is incorrect. Now we are going to use the reference BED file.
Our coverage is 3.6 and our reads BAM file has 22 gigabytes.
I'll write when we have results, thanks again Jose.

Cheers,
Fran.

**Comment by fanavarro** [comment]
Hi again. We ran nanosv on october 10. The nohup file shows the following for now (after five days):
```
Wed Oct 10 11:31:13 2018 Busy with calculating the coverage distribution...
Wed Oct 10 14:06:28 2018 Busy with parsing bam file...
```
In this case, we have used minimap2 with the map-ont option (for Oxford nanopore reads) for the alignment. Also, we are using an HG38 bed file, which is the unique that we found, but it only contains the following lines:
```
chr10	0	133797422
chr11	0	135086622
chr12	0	133275309
chr13	0	114364328
chr14	0	107043718
chr15	0	101991189
chr16	0	90338345
chr17	0	83257441
chr18	0	80373285
chr19	0	58617616
chr1	0	248956422
chr20	0	64444167
chr21	0	46709983
chr22	0	50818468
chr2	0	242193529
chr3	0	198295559
chr4	0	190214555
chr5	0	181538259
chr6	0	170805979
chr7	0	159345973
chr8	0	145138636
chr9	0	138394717
chrM	0	16569
chrX	0	156040895
chrY	0	57227415
```
Also in this case we saw how multiple processes of nanosv appeared (due to multithreading, we think). After several minutes, only one nanosv process remained, with a cpu usage near to 100%, and a a file called "snp_positions_used_for_phasing.bed" appeared. For now, that file and the output vcf file remains empty. We have though that it is possible that nanosv does not print to the files immediately and it is working on latter stages although we can not see it.

**Comment by jaesvi** [comment]
Hi,
The BED file you are providing makes NanoSV check every position in the genome for coverage, instead of the 1,000,000 we are looking for. I prepared a custom BED file for you (attached).
[hg38_genome_sample.bed.zip](https://github.com/mroosmalen/nanosv/files/2491380/hg38_genome_sample.bed.zip)
For future reference, we updated the nanosv/scripts/create_random_position_bed.sh to make it easier to create a custom BED file for any genome.

**Comment by jaesvi** [comment]
Hi Fran,
Have you managed to run NanoSV?
Best,
Jose

**Comment by fanavarro** [comment]
Hi Jose. I forgot to write the answer, sorry... Finally we were able to run nanosv successfully with the new BED file, thank you very much!

Cheers,
Fran.

**Comment by astulaaa** [comment]
Hi, I used the same hg38_genome_sample.bed.zip file shared for BED and my run on a human genome which does not have an extraordinary coverage is taking 5 days already. Last mention in log file is from the first day "Busy with parsing bam file...". Another run was with the default bed provided but the process looks same. Is it expected behaviour? How long I can expect it to take?
