### ISSUE TITLE
VCF Filters

### ISSUE THREAD

**Issue by mpabloperez** [mroosmalen/nanosv#54]
Dear developers,

Using the default config.ini file in the program repository, I don't know how to filter the output vcf properly. What would be the command parameters that would avoid false positives? In the paper you state: 

> _We run NanoSV on the MinION data of each patient using the default parameters: “-t 8 -s 10 -p 0.70 -m 20 -d 10 -c 2 -f 100 -u 20 -r 300 -w 1000 -n 2 -q 80 -i 0.80 -g 100 -y 20”_

How is this translated to the config.ini file format? On the other hand, why is the filter MapQual set to 80 by default? Do you get something with no MapQual flag? 

Thank you in advance.

**Comment by mroosmalen** [comment]
We didn't change the default settings in the config.ini. So if you want to use the default settings you can use the default config.ini file. If you want to change something you need to create your own ini file with only the parameters that you want to change. For example:
```
[Output filter options]
mapq_flag = 50
```
The MapQual flag is set on 80 by default because we experienced that SV's with a higher mapping quality are likely more true than SV's with a lower mapping quality. This 80 is based on LAST mapping (has a maximum mapping quality value of 100), if you use Minimap2 or NGMLR you should lower this (e.g. 50) , because the maximum mapping quality for these is 60.
